### ISSUE TITLE
Image does not work on M1 MacBook's(arm64)

### ISSUE THREAD

**Issue by jayson31** [isholgueras/chrome-headless#1]
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[0709/091839.560661:ERROR:file_path_watcher_linux.cc(318)] inotify_init() failed: Function not implemented (38)
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
DevTools listening on ws://0.0.0.0:9222/devtools/browser/2e133d2e-a0e4-4725-b331-267836ea4b3e
qemu: unknown option 'type=gpu-process'
qemu: unknown option 'type=utility'
[0709/091840.075841:WARNING:gpu_process_host.cc(1188)] The GPU process has crashed 1 time(s)
qemu: unknown option 'type=gpu-process'
[0709/091840.162766:WARNING:gpu_process_host.cc(1188)] The GPU process has crashed 2 time(s)
qemu: unknown option 'type=gpu-process'
[0709/091840.178481:WARNING:gpu_process_host.cc(1188)] The GPU process has crashed 3 time(s)
qemu: unknown option 'type=gpu-process'
[0709/091840.193563:WARNING:gpu_process_host.cc(1188)] The GPU process has crashed 4 time(s)
qemu: unknown option 'type=gpu-process'
[0709/091840.237669:WARNING:gpu_process_host.cc(1188)] The GPU process has crashed 5 time(s)
qemu: unknown option 'type=utility'
qemu: unknown option 'type=gpu-process'
[0709/091840.280583:WARNING:gpu_process_host.cc(1188)] The GPU process has crashed 6 time(s)
[0709/091840.280793:FATAL:gpu_data_manager_impl_private.cc(894)] The display compositor is frequently crashing. Goodbye.
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
qemu: unknown option 'type=utility'

I get the above log message when I try to run the image in docker on a m1 MacBook pro. The current image is just build for amd64 which does not work as expected on arm64 architecture(m1) @isholgueras could you provide a image that would work on arm64 architecture?

System details:
Macbook Pro
Chip: Apple M1
Memory: 16 GB

**Comment by rfay** [comment]
It's pretty easy to build multi-platform images using `docker buildx`, that's how the official ddev images are built. The basics are at https://www.docker.com/blog/multi-platform-docker-builds/, Docker 20 supports buildx directly. Happy to help.

**Comment by jayson31** [comment]
@rfay I was able to build the current docker image for arm architecture but I get an error "Unable to locate package google-chrome-stable" when trying to build the base image for arm architecture i.e justinribeiro/chrome-headless.

Console Output for the error log:

#6 88.51 E: Unable to locate package google-chrome-stable
------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c apt-get update && apt-get install -y 	apt-transport-https 	ca-certificates 	curl 	gnupg 	--no-install-recommends 	&& curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - 	&& echo "deb https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list 	&& apt-get update && apt-get install -y 	google-chrome-stable 	fontconfig 	fonts-ipafont-gothic 	fonts-wqy-zenhei 	fonts-thai-tlwg 	fonts-kacst 	fonts-symbola 	fonts-noto 	fonts-freefont-ttf 	--no-install-recommends 	&& apt-get purge --auto-remove -y curl gnupg 	&& rm -rf /var/lib/apt/lists/*]: exit code: 100

**Comment by rfay** [comment]
If you do the steps manually, you get
`N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://dl.google.com/linux/chrome/deb stable InRelease' doesn't support architecture 'arm64'`

So these things are just one step after another :)

The *chromium* browser is the open-source version of Chrome, and has arm64 packages for Debian, https://wiki.debian.org/Chromium

I know that's probably a hard exploration, but it just might work.

**Comment by rfay** [comment]
Looks like chromium may be a totally legit way to do headless chrome, as one would expect:

https://gist.github.com/ipepe/94389528e2263486e53645fa0e65578b

**Comment by isholgueras** [comment]
Thanks @jayson31 for creating the ticket. I'm not sure if I already replied you with an email but this is better.

Thanks @rfay for reply. 

TBH, I don't know how things are working on M1 as I don't own one, but searching for similar issues I've found we can disallow the GPU with these 2 arguments:
```
--disable-gpu
--disable-software-rasterizer
```

I don't know how this could work but I will give a try.

**Comment by isholgueras** [comment]
I've pushed a new image, @jayson31 disabling the software rasterizer. https://hub.docker.com/repository/docker/isholgueras/chrome-headless/general

Can you please check if the latest works well? Thanks!

**Comment by jayson31** [comment]
Hi Inacio,

This still does not work on M1 Mac.

I get the below errors in docker logs:

qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[0922/091016.481150:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[0922/091016.501640:ERROR:file_path_watcher_linux.cc(326)] inotify_init() failed: Function not implemented (38)
[0922/091016.567429:WARNING:headless_browser_main_parts.cc(106)] Cannot create Pref Service with no user data dir.
DevTools listening on ws://0.0.0.0:9222/devtools/browser/8972a397-146c-4d07-9d3f-d54b41870a8d
[0922/091016.630588:ERROR:gpu_process_host.cc(996)] GPU process launch failed: error_code=1002
[0922/091016.632362:WARNING:gpu_process_host.cc(1316)] The GPU process has crashed 1 time(s)
qemu: unknown option 'type=utility'
[0922/091016.687619:ERROR:gpu_process_host.cc(996)] GPU process launch failed: error_code=1002
[0922/091016.687699:WARNING:gpu_process_host.cc(1316)] The GPU process has crashed 2 time(s)
[0922/091016.735935:ERROR:simple_backend_impl.cc(81)] Failed to create directory: /opt/google/chrome/Code Cache/js
[0922/091016.736009:ERROR:simple_backend_impl.cc(81)] Failed to create directory: /opt/google/chrome/Code Cache/wasm
[0922/091016.738495:ERROR:simple_backend_impl.cc(81)] Failed to create directory: /opt/google/chrome/Code Cache/wasm
[0922/091016.739090:ERROR:simple_backend_impl.cc(81)] Failed to create directory: /opt/google/chrome/Code Cache/js
[0922/091016.738902:ERROR:simple_backend_impl.cc(757)] Simple Cache Backend: wrong file structure on disk: 1 path: /opt/google/chrome/Code Cache/wasm
[0922/091016.739930:ERROR:simple_backend_impl.cc(757)] Simple Cache Backend: wrong file structure on disk: 1 path: /opt/google/chrome/Code Cache/js
[0922/091016.793734:ERROR:gpu_process_host.cc(996)] GPU process launch failed: error_code=1002
[0922/091016.793842:WARNING:gpu_process_host.cc(1316)] The GPU process has crashed 3 time(s)
[0922/091016.794154:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

Screenshots of docker: https://monosnap.com/file/3vV1jLry5wYAtZKCRo19MQR9swRQsZ and https://monosnap.com/file/B4mpb7umnamzwmEOS7JiG5PqGU1yeE

**Comment by isholgueras** [comment]
Uhm... 

I've found this issue in travis: https://github.com/travis-ci/travis-web/commit/8c96918b2f3c8fe64f87824bcee58fb569439c0f

Maybe M1 is trying to access a GPU and we're removing the ability to use GPU. Try this new version, please.

**Comment by rfay** [comment]
Mostly it's not really to be expected that Docker's amd64 emulation will work perfectly on arm64, and a crash like this is often the outcome. It's very much a hack and arm64 images are what we really want. 

IMO Switching to chromium, which has arm64 packages and images would be the best path forward.

**Comment by isholgueras** [comment]
Thanks a lot for the PR, @rfay ,
Let me check your PR

**Comment by pjg** [comment]
FWIW, to fix the GPU process crashing the following flags need to be enabled (Chromium/Chrome 111):

```
  --use-angle=swiftshader
  --use-gl=angle
  --in-process-gpu
```

And the following commented out:

```
  // --disable-gpu
```

**Comment by rfay** [comment]
Just a note that most people are using the ddev-selenium-headless-chrome image these days @pjg , https://github.com/ddev/ddev-selenium-standalone-chrome
